name: mdcharts_example
description: Demonstrates how to use the mdcharts package.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  mdcharts:
    path: ../

  intl: ^0.17.0
  rxdart: ^0.27.3
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
